// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JobsCompany struct {
	ID          pgtype.UUID
	Title       string
	Description string
	CreateTime  pgtype.Timestamptz
	UpdateTime  pgtype.Timestamptz
}
